language: python

virtualenv:
  system_site_packages: true

# This (sudo: false) is needed to "run on container-based infrastructure" on
# which cache: is available
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: required

addons:
  postgresql: "9.6"

env:
  matrix:
    - OMERO_VERSION=5.4.0

before_install:
  - pip install restructuredtext_lint
  - pip install flake8 pycodestyle pep8-naming
  - flake8 .
  - rst-lint README.rst
  - export PATH=/usr/bin/:$PATH
  - sudo apt-get install -y zeroc-ice35
  # populate metadata
  - sudo apt-get install -y python-{pillow,numpy,tables}
  # for make movie
  - sudo apt-get install -y mencoder


before_script:
    - psql -c "create user omero with password 'omero';" -U postgres
    - psql -c "create database omero with owner omero;" -U postgres
    - mkdir $HOME/OMERO
    - echo "config set omero.data.dir $HOME/OMERO" > $HOME/config.omero
    - echo "config set omero.db.name omero" >> $HOME/config.omero
    # required so the server can start
    - echo "config set Ice.IPv6 0" >> $HOME/config.omero

script:
  # The installation is run in the virtual env
  # Required to explicitly activate it
  - source $HOME/virtualenv/python2.7_with_system_site_packages/bin/activate
  - OMERO_VERSION=$OMERO_VERSION ./travis-build
